### PR TITLE
Times page

### PR DESCRIPTION
**Pull request by saretoduncan**
This is a clone web page of the new york times web page. Pure HTML and CSS have been used. For best results, I recommend using a google-chrome browser.

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @saretoduncan  :wave:

__You've made laudable progress in this project :clap:__

- The page contents are complete and rending well :100: 
- Your readme is awesome :+1: 

__Overall, this is a great starting point. However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] Let's improve your Readme by adding the exact git command to clone your repository in the setup section. i.e. `git clone <repo-url>`
- [x] Still, on the Readme, the `Issues page` link under the `Contributing` section seems to be broken. Kindly fix it.
- [x] There seems to be a slight difference in the buttons on the navbar. Check the images below and make necessary changes.
**Original Navbar**
original
**Your Navbar**
clone

- [x] The dates are missing in the `More in Space and Astronomy` articles. 
**Original**
original
**Clone**
clone
  - This is applicable to the `Editors’ Picks` section also. 
- [x] Check my inline comment(s) below for other recommended changes.

**[ OPTIONAL CHANGES ]**

- [ ] If you're in the mood :wink: you can add the fixed footer (that sticks to the bottom part of the screen) as seen on the original page.
st



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by SmithVyne — CHANGES_REQUESTED** [review]
### Changes Required 🤕 👍 
Hello @saretoduncan you have a nice project here, but we just need a few more fixes so it can be approved.
I found a couple of sections of the page where things fell out of place. 

- The Login/Signup buttons
image

-  The Theory of Inflation section - Here the images are overlapping the text
image

Make these changes and request another code review. You should get it approved this time.


You can also reach out to me on slack, **@SmithVyne** if you have any other questions.

**Review by SmithVyne — APPROVED** [review]
### Approved  🎖️ 🏅 😄 
Hi, congratulations on making the required changes. Your project is now approved.
You can now merge this branch.
You can reach out to me on Slack, **@smithvyne** if you have any further questions.

**Comment by saretoduncan** [comment]
> ### Approved   
> Hi, congratulations on making the required changes. Your project is now approved.
> You can now merge this branch.
> You can reach out to me on Slack, **@SmithVyne** if you have any further questions.

Thank you

**Pull request closed without merging**
